import type { Work } from './types.ts';

// Original fictional works for the local frontend sample. Source labels are
// display-only examples; this catalogue has no connection to either service.
export const works: Work[] = [
  {
    id: 'rain',
    title: '雨停之前',
    subtitle: '在最后一班电车到来以前',
    author: '林间折页',
    source: 'JM',
    cover: '/covers/rain.svg',
    accent: '#a65335',
    tags: ['青春', '短篇', '治愈'],
    description: '街角的旧候车亭里，两个总在雨天相遇的人，交换着从未寄出的明信片。关于告别、等待，以及终于说出口的一句话。',
    chapters: 8,
    pages: 192,
    sizeMB: 144,
    status: 'ready',
    finished: true,
    updated: '2026-09-08',
  },
  {
    id: 'sea',
    title: '海街来信',
    subtitle: '潮汐会替我们记住地址',
    author: '七岛灯',
    source: 'Pica',
    cover: '/covers/sea.svg',
    accent: '#438d87',
    tags: ['日常', '小镇', '群像'],
    description: '重开祖母留下的邮局后，澄在一座慢半拍的海边小城里，收到了一封写给明年的信。每次潮汐，都带来一个新的故事。',
    chapters: 12,
    pages: 264,
    sizeMB: 186,
    status: 'ready',
    finished: false,
    updated: '2026-09-08',
  },
  {
    id: 'train',
    title: '无人列车',
    subtitle: '下一站，不在地图上',
    author: '远野标本',
    source: 'JM',
    cover: '/covers/train.svg',
    accent: '#6a6a65',
    tags: ['悬疑', '旅行', '黑白'],
    description: '零点十三分，废弃车站驶来一列没有司机的列车。车窗外的每个站台，都藏着乘客想要重新选择的那一天。',
    chapters: 6,
    pages: 156,
    sizeMB: 128,
    status: 'ready',
    finished: true,
    updated: '2026-09-08',
  },
  {
    id: 'moon',
    title: '月面花园',
    subtitle: '把春天种在没有风的地方',
    author: '藤白眠',
    source: 'Pica',
    cover: '/covers/moon.svg',
    accent: '#789da9',
    tags: ['科幻', '花草', '治愈'],
    description: '月球植物站最后一名实习园丁，发现温室里有一株只在地球日落时开花的植物。她开始为这片寂静的土地记录四季。',
    chapters: 10,
    pages: 224,
    sizeMB: 172,
    status: 'ready',
    finished: false,
    updated: '2026-09-08',
  },
  {
    id: 'summer',
    title: '夏日观测',
    subtitle: '关于云、蝉鸣与第七个夏天',
    author: '日向藻',
    source: 'Pica',
    cover: '/covers/summer.svg',
    accent: '#b39143',
    tags: ['青春', '校园', '日常'],
    description: '三个人、一本气象手册和一间即将关闭的天文社活动室。他们决定在毕业前，认真记录这个夏天所有微不足道的变化。',
    chapters: 14,
    pages: 288,
    sizeMB: 212,
    status: 'owned',
    finished: true,
    updated: '2026-09-08',
  },
  {
    id: 'flight',
    title: '白昼航线',
    subtitle: '向着云层另一侧的故乡',
    author: '岬与风',
    source: 'JM',
    cover: '/covers/flight.svg',
    accent: '#5c91aa',
    tags: ['冒险', '旅行', '成长'],
    description: '在岛屿依靠小型邮政飞机相连的世界里，一名见习领航员接过了父亲留下的旧航图。没有标注的空白处，或许就是归途。',
    chapters: 9,
    pages: 216,
    sizeMB: 165,
    status: 'ready',
    finished: false,
    updated: '2026-09-08',
  },
  {
    id: 'bookshop',
    title: '雾中书店',
    subtitle: '为没有结尾的故事留一盏灯',
    author: '薄荷山羊',
    source: 'Pica',
    cover: '/covers/bookshop.svg',
    accent: '#406b58',
    tags: ['奇幻', '小镇', '日常'],
    description: '只有大雾弥漫时才开门的书店，出售的书都少了最后一页。新来的店员需要先听完顾客的故事，才能找到属于他们的结尾。',
    chapters: 12,
    pages: 252,
    sizeMB: 184,
    status: 'ready',
    finished: false,
    updated: '2026-09-08',
  },
  {
    id: 'echo',
    title: '星光回声',
    subtitle: '宇宙很安静，直到你开始歌唱',
    author: '南河零',
    source: 'JM',
    cover: '/covers/echo.svg',
    accent: '#8a74a7',
    tags: ['科幻', '音乐', '群像'],
    description: '深夜电台收到了一段来自遥远星系的旋律。四个互不相识的人循着信号相遇，尝试完成一首跨越光年的合奏。',
    chapters: 7,
    pages: 168,
    sizeMB: 138,
    status: 'review',
    finished: false,
    updated: '2026-09-08',
  },
];
